
version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      # Install the latest version of the AWS CLI if needed
      - echo Installing AWS CLI...
      - pip install --upgrade awscli
      # Install Maven if required
      - echo Installing Maven...
      - apt-get install -y maven
      # Authenticate Docker to AWS ECR
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 381491946813.dkr.ecr.ap-south-1.amazonaws.com

  pre_build:
    commands:
      # Define variables for repository and image
      - REPOSITORY_URI=381491946813.dkr.ecr.ap-south-1.amazonaws.com/satishdemo1
      - IMAGE_TAG=latest
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG .

  build:
    commands:
      # Tag the Docker image
      - echo Tagging the Docker image...
      - docker tag $REPOSITORY_URI:$IMAGE_TAG $REPOSITORY_URI:$IMAGE_TAG

  post_build:
    commands:
      # Push the Docker image to ECR
      - echo Pushing the Docker image to Amazon ECR...
      - docker push $REPOSITORY_URI:$IMAGE_TAG

artifacts:
  files:
    - '**/*'

