


version: 0.2

env:
  variables:
    AWS_REGION: ap-south-1
    ECR_REPOSITORY_URI: public.ecr.aws/x1x2l5r7/mydemoecrrepo

phases:
  install:
    runtime-versions:
      java: corretto17  # Updated to use Java 17
    commands:
      - echo Installing dependencies...
      - mvn install -DskipTests  # Install Maven dependencies without running tests
      - echo Logging in to Amazon ECR...
      - $(aws ecr-public get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REPOSITORY_URI)

  pre_build:
    commands:
      - echo Building the Spring Boot application...
      - mvn package -DskipTests  # Package the application as a JAR

  build:
    commands:
      - echo Building the Docker image...
      - docker build -t mydemoecrrepo .
      - echo Tagging the Docker image...
      - docker tag mydemoecrrepo:latest $ECR_REPOSITORY_URI:latest

  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push $ECR_REPOSITORY_URI:latest
      - echo Build completed on `date`

artifacts:
  files:
    - '**/target/*.jar'  # Adjust this path if your JAR location differs
